apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:latest 
        args: ["--appendonly", "yes"]
        ports:
          - name: redis
            containerPort: 6379
        volumeMounts:
          - name: redis-volume
            mountPath: /data
        env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-persistent-volume-claim