kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: production-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: staging-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: development-pvc
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi