apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  namespace: production
spec:
  replicas: 5
  selector:
    matchLabels:
      name: nginx-server
  template:
    metadata:
      labels:
        name: nginx-server
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  namespace: production
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: nginx-server