apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-deployment
  namespace: development
  labels:
    app: drone
spec:
  selector:
    matchLabels:
      app: drone
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
      - name: drone
        image: drone/drone:1.6.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443
        envFrom:
        - secretRef:
            name: drone-secret
        - configMapRef:
            name: drone-config
---
apiVersion: v1
kind: Service
metadata:
  name: drone-service
  namespace: development
  labels:
    app: drone
spec:
  type: ClusterIP
  selector:
    app: drone
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drone-ingress
  namespace: development
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "drone.kub3.dev"
    secretName: le-drone-kub3-dev-cert-tls
  rules:
  - host: drone.kub3.dev
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: drone
            port:
              number: 80