apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - identitty.kub3.dev
      secretName: le-identitty-kub3-dev-cert-tls
  rules:
    - host: identitty.kub3.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080