apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: development
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: keycloak